-- H2 2.2.224;
CREATE USER IF NOT EXISTS "SA" SALT '94cd781c16ead2fa' HASH '2f050869cc4548eebb3a274ebc8db8d08b5a6e47404e38b3031acf6579a1486a' ADMIN;
CREATE CACHED TABLE "PUBLIC"."PROJECT"(
    "IDX" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "TITLE" CHARACTER VARYING(255),
    "PERIOD" CHARACTER VARYING(255),
    "UNIT" CHARACTER VARYING(255),
    "IMAGES" CHARACTER VARYING(1000),
    "SUBJECT" CHARACTER VARYING(1000),
    "FUNCTION" CHARACTER VARYING(1000),
    "FRONTEND" CHARACTER VARYING(255),
    "BACKEND" CHARACTER VARYING(255),
    "DATABASE" CHARACTER VARYING(255),
    "REVIEW" CHARACTER VARYING(2000),
    "GITHUB" CHARACTER VARYING(500)
);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.PROJECT;
INSERT INTO "PUBLIC"."PROJECT"(title, period, unit, images, subject, function, frontend, backend, database, review, github)
values('결혼정보회사 매칭 사이트', '2024년 3월 7일 ~ 2024년 4월 4일', '4인 팀프로젝트', 'final_홈화면,final_매칭페이지,final_상대프로필,final_매칭현황,final_채팅1,final_채팅2', '결혼 및 출산에 부정적인 2,30대 청년들에게<br>건전한 결혼 매칭 시스템을 제공함으로써<br>결혼율을 높이고 사회적 공헌을 실천하고자 개발하였습니다.', '멤버쉽 가입(결제) 및 환불!매칭 상대 검색, 매칭 신청, 매칭 수락/거절/보류!회원 등급 책정, 회원 신고 및 처리!매칭 성사 회원 간 채팅', 'JSP, HTML, CSS, JavaScript', 'JAVA, JSP, spring', 'Oracle SQL Developer', '웹소켓을 활용하여 실시간으로 매칭과 채팅이 이루어지도록<br>구성하여 회원간의 즉각적인 소통이 가능하도록 제작하고자 노력하였습니다.<br>복잡한 쿼리문을 사용해보면서 SQL 활용 능력을 향상시킬 수 있었고,<br>spring 에 대한 이해가 한층 깊어지게 된 프로젝트였습니다.<br>또한 다수의 팀원들과 처음으로 협업을 하면서<br>팀원간 소통의 중요성을 배울 수 있었습니다.', 'https://github.com/OKCHANGHYEOK/finalProject');
INSERT INTO "PUBLIC"."PROJECT"(title, period, unit, images, subject, function, frontend, backend, database, review, github)
values('영화정보 제공 및 리뷰 사이트', '2024년 1월 8일 ~ 2024년 1월 14일', '2인 팀프로젝트', 'mini_홈화면,mini_영화상세보기,mini_영화검색', '평소에 영화를 좋아하여 자주 시청하는 편인데<br>스트리밍 사이트에서 영화에 대한 평가를 남기고,<br>서로 공유할 수 있는 게시판이 있었으면 좋겠다는 생각이 들어서 만들게 되었습니다.', '영화 좋아요 및 내가 좋아요한 영화 모아보기!영화 검색 및 정렬!영화 별점 남기기!리뷰 게시판', 'JSP, HTML, CSS, JavaScript', 'JAVA, JSP', 'Oracle SQL Developer', '회원가입시 중복 아이디 검사 , 영화 좋아요 등의 기능을 만들면<br>쿼리문을 작성하는 능력을 발전시킬 수 있었습니다.<br>Model, View, Controller로 이루어진 웹 애플리케이션의 동작 흐름에 대해<br>전반적인 이해를 높일 수 있었던 프로젝트였습니다.<br>', 'https://github.com/OKCHANGHYEOK/itbank/tree/master/JSP/mini');